//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busqueda
    {
        public Busqueda()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id_Busqueda { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public int Id_Puesto { get; set; }
        public string Descripcion { get; set; }
        public string Referencia { get; set; }
        public bool Activa { get; set; }
    
        public virtual Puestos Puestos { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
