//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteCabecera
    {
        public ComprobanteCabecera()
        {
            this.ComprobanteDetalle = new HashSet<ComprobanteDetalle>();
        }
    
        public int idComprobanteCabecera { get; set; }
        public string letra { get; set; }
        public int numero { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipoComprobante { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idSucursal { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoComprobante TipoComprobante1 { get; set; }
        public virtual ICollection<ComprobanteDetalle> ComprobanteDetalle { get; set; }
    }
}
