//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteDetalle
    {
        public int idComprobanteDetalle { get; set; }
        public int idComprobanteCabecera { get; set; }
        public string detalle { get; set; }
        public int Id_Servicio { get; set; }
        public int cantidad { get; set; }
    
        public virtual ComprobanteCabecera ComprobanteCabecera { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
