//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public int Id_CV { get; set; }
        public int idUsuario { get; set; }
        public int Id_DatosPersonales { get; set; }
        public int Id_EstudiosFormales { get; set; }
        public int Id_ModuloComposicion { get; set; }
        public bool Activo { get; set; }
    
        public virtual DatosPersonales DatosPersonales { get; set; }
        public virtual EstudiosFormales EstudiosFormales { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
