//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosPersonales
    {
        public DatosPersonales()
        {
            this.CV = new HashSet<CV>();
        }
    
        public int Id_DatosPersonales { get; set; }
        public string ApellidoPostulante { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombrePostulante { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Numero { get; set; }
        public string Piso { get; set; }
        public string Dto { get; set; }
        public string CodPostal { get; set; }
        public string email { get; set; }
        public Nullable<int> CantidadHijos { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ICollection<CV> CV { get; set; }
    }
}
