//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public int Id_Estado { get; set; }
        public string DescripcionEstado { get; set; }
        public string Habilitado { get; set; }
        public string EstIT { get; set; }
        public string EstFecha { get; set; }
        public string EstHora { get; set; }
        public string EstUsuario { get; set; }
    }
}
