//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiosFormales
    {
        public EstudiosFormales()
        {
            this.CV = new HashSet<CV>();
        }
    
        public int Id_EstudiosFormales { get; set; }
        public string Nivel { get; set; }
        public string Institucion { get; set; }
        public string Titulo { get; set; }
        public string Estado { get; set; }
        public int PorcAvance { get; set; }
        public int PeriodoDesde { get; set; }
        public int PeriodoHasta { get; set; }
    
        public virtual ICollection<CV> CV { get; set; }
    }
}
