//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalidadBarrio
    {
        public int Id_LB { get; set; }
        public string NombreLocalidad { get; set; }
        public bool Activo { get; set; }
        public int Id_Municipio { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
