//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idPermiso { get; set; }
        public int CodigoPermiso { get; set; }
        public string Detalle { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
