//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostulanteIdioma
    {
        public int Id_PostulanteIdioma { get; set; }
        public int Id_Idioma { get; set; }
        public int Id_NivelManejo { get; set; }
        public int idUsuario { get; set; }
        public string Centro { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual NivelManejo NivelManejo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
