//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Cliente = new HashSet<Cliente>();
            this.CV = new HashSet<CV>();
            this.PostulanteIdioma = new HashSet<PostulanteIdioma>();
            this.Grupo = new HashSet<Grupo>();
            this.Busqueda = new HashSet<Busqueda>();
            this.Permiso = new HashSet<Permiso>();
        }
    
        public int idUsuario { get; set; }
        public string password { get; set; }
        public string detalle { get; set; }
        public bool activo { get; set; }
        public string usr { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<CV> CV { get; set; }
        public virtual ICollection<PostulanteIdioma> PostulanteIdioma { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<Busqueda> Busqueda { get; set; }
        public virtual ICollection<Permiso> Permiso { get; set; }
    }
}
