
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Code52.i18n
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }


        // ######### BARRA DE NAVEGACIÓN SUPERIOR #############
        internal static string ListadoBusquedasVigentes
        {
            get
            {
                return ResourceManager.GetString("ListadoBusquedasVigentes", resourceCulture);
            }
        }

        internal static string Servicios
        {
            get
            {
                return ResourceManager.GetString("Servicios", resourceCulture);
            }
        }
        internal static string Busqueda
        {
            get
            {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }

     

        internal static string ConsultaServicios
        {
            get
            {
                return ResourceManager.GetString("ConsultaServicios", resourceCulture);
            }
        }

        internal static string Consultor
        {
            get
            {
                return ResourceManager.GetString("Consultor", resourceCulture);
            }
        }

        internal static string Postulantes
        {
            get
            {
                return ResourceManager.GetString("Postulantes", resourceCulture);
            }
        }

        internal static string Postulante
        {
            get
            {
                return ResourceManager.GetString("Postulante", resourceCulture);
            }
        }


        internal static string evaluarPostulantes
        {
            get
            {
                return ResourceManager.GetString("evaluarPostulantes", resourceCulture);
            }
        }

        internal static string PostulantesporBusqueda
        {
            get
            {
                return ResourceManager.GetString("PostulantesporBusqueda", resourceCulture);
            }
        }
        
        internal static string GestionarAvisos
        {
            get
            {
                return ResourceManager.GetString("GestionarAvisos", resourceCulture);
            }
        }


        internal static string Avisos
        {
            get
            {
                return ResourceManager.GetString("Avisos", resourceCulture);
            }
        }

        internal static string Campanias
        {
            get
            {
                return ResourceManager.GetString("Campanias", resourceCulture);
            }
        }


        internal static string GenerarCampania
        {
            get
            {
                return ResourceManager.GetString("GenerarCampania", resourceCulture);
            }
        }

        internal static string Campania
        {
            get
            {
                return ResourceManager.GetString("Campania", resourceCulture);
            }
        }



        internal static string Productos
        {
            get
            {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }

        internal static string NuevoProducto
        {
            get
            {
                return ResourceManager.GetString("NuevoProducto", resourceCulture);
            }
        }

        internal static string NuevaBusqueda
        {
            get
            {
                return ResourceManager.GetString("NuevaBusqueda", resourceCulture);
            }
        }

        internal static string Administracion
        {
            get
            {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }

        internal static string AdminPerfil
        {
            get
            {
                return ResourceManager.GetString("AdminPerfil", resourceCulture);
            }
        }

        internal static string Registrarse
        {
            get
            {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }

        internal static string IniciarSesion
        {
            get
            {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }

        internal static string AltaCV
        {
            get
            {
                return ResourceManager.GetString("AltaCV", resourceCulture);
            }
        }

        internal static string efectivo
        {
            get
            {
                return ResourceManager.GetString("efectivo", resourceCulture);
            }
        }

        internal static string transferencia
        {
            get
            {
                return ResourceManager.GetString("transferencia", resourceCulture);
            }
        }

        internal static string legajo
        {
            get
            {
                return ResourceManager.GetString("legajo", resourceCulture);
            }
        }

        internal static string fechaNacimiento
        {
            get
            {
                return ResourceManager.GetString("fechaNacimiento", resourceCulture);
            }
        }

        internal static string puesto
        {
            get
            {
                return ResourceManager.GetString("puesto", resourceCulture);
            }
        }

        internal static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        internal static string Ingresar
        {
            get
            {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }

        internal static string CerrarSesion
        {
            get
            {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }

        internal static string Pedidos
        {
            get
            {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }

        internal static string Confirmados
        {
            get
            {
                return ResourceManager.GetString("Confirmados", resourceCulture);
            }
        }

        internal static string ListadoPedidos
        {
            get
            {
                return ResourceManager.GetString("ListadoPedidos", resourceCulture);
            }
        }

        internal static string ListadoPedidosAConfirmar
        {
            get
            {
                return ResourceManager.GetString("ListadoPedidosAConfirmar", resourceCulture);
            }
        }

        internal static string ListadoPedidosConfirmados
        {
            get
            {
                return ResourceManager.GetString("ListadoPedidosConfirmados", resourceCulture);
            }
        }

        internal static string ListadoPedidosCancelados
        {
            get
            {
                return ResourceManager.GetString("ListadoPedidosCancelados", resourceCulture);
            }
        }

        internal static string Facturacion
        {
            get
            {
                return ResourceManager.GetString("Facturacion", resourceCulture);
            }
        }

        internal static string Factura
        {
            get
            {
                return ResourceManager.GetString("Factura", resourceCulture);
            }
        }

        internal static string Bitacora
        {
            get
            {
                return ResourceManager.GetString("Bitacora", resourceCulture);
            }
        }

        internal static string AltaEmpleado
        {
            get
            {
                return ResourceManager.GetString("AltaEmpleado", resourceCulture);
            }
        }
        
        internal static string ListadoFactura
        {
            get
            {
                return ResourceManager.GetString("ListadoFactura", resourceCulture);
            }
        }

        internal static string Modulo
        {
            get
            {
                return ResourceManager.GetString("Modulo", resourceCulture);
            }
        }

        internal static string Tipo
        {
            get
            {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }

        internal static string ListadoProductosVigentes
        {
            get
            {
                return ResourceManager.GetString("ListadoProductosVigentes", resourceCulture);
            }
        }

        internal static string ListaBusquedas
        {
            get
            {
                return ResourceManager.GetString("ListaBusquedas", resourceCulture);
            }
        }


        internal static string Imagen
        {
            get
            {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
                
        internal static string Detalle
        {
            get
            {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }

        // ######### BARRA DE NAVEGACIÓN LATERAL #############
      


        internal static string Secciones
        {
            get
            {
                return ResourceManager.GetString("Secciones", resourceCulture);
            }
        }
        internal static string Modulos
        {
            get
            {
                return ResourceManager.GetString("Modulos", resourceCulture);
            }
        }

        internal static string AntenasHF
        {
            get
            {
                return ResourceManager.GetString("AntenasHF", resourceCulture);
            }
        }
        internal static string DatosPersonales
        {
            get
            {
                return ResourceManager.GetString("DatosPersonales", resourceCulture);
            }
        }

        internal static string EstudiosFormales
        {
            get
            {
                return ResourceManager.GetString("EstudiosFormales", resourceCulture);
            }
        }
        internal static string ExperienciaLaboral
        {
            get
            {
                return ResourceManager.GetString("ExperienciaLaboral", resourceCulture);
            }
        }

        internal static string AntenasVHF
        {
            get
            {
                return ResourceManager.GetString("AntenasVHF", resourceCulture);
            }
        }

        internal static string AntenasHilo
        {
            get
            {
                return ResourceManager.GetString("AntenasHilo", resourceCulture);
            }
        }

        internal static string Torres
        {
            get
            {
                return ResourceManager.GetString("Torres", resourceCulture);
            }
        }

        internal static string Rotores
        {
            get
            {
                return ResourceManager.GetString("Rotores", resourceCulture);
            }
        }

        internal static string Accesorios
        {
            get
            {
                return ResourceManager.GetString("Accesorios", resourceCulture);
            }
        }

        internal static string Novedades
        {
            get
            {
                return ResourceManager.GetString("Novedades", resourceCulture);
            }
        }

        internal static string Promociones
        {
            get
            {
                return ResourceManager.GetString("Promociones", resourceCulture);
            }
        }


        // ######### VISTA ALTA CLIENTE #############

        internal static string altaCliente
        {
            get
            {
                return ResourceManager.GetString("altaCliente", resourceCulture);
            }
        }

        internal static string Campo
        {
            get
            {
                return ResourceManager.GetString("Campo", resourceCulture);
            }
        }
        
        internal static string Valor
        {
            get
            {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }

        internal static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        internal static string Contrasena
        {
            get
            {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }

        internal static string ConfirmarContrasena
        {
            get
            {
                return ResourceManager.GetString("ConfirmarContrasena", resourceCulture);
            }
        }
        
        internal static string Nombre
        {
            get
            {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }

        internal static string email
        {
            get
            {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }

        internal static string ListadoDePedidos
        {
            get
            {
                return ResourceManager.GetString("ListadoDePedidos", resourceCulture);
            }
        }

        internal static string ListadoDePedidosAConfirmar
        {
            get
            {
                return ResourceManager.GetString("ListadoDePedidosAConfirmar", resourceCulture);
            }
        }

        internal static string ListadoDePedidosCancelados
        {
            get
            {
                return ResourceManager.GetString("ListadoDePedidosCancelados", resourceCulture);
            }
        }

        internal static string ListadoDePedidosFinalizados
        {
            get
            {
                return ResourceManager.GetString("ListadoDePedidosFinalizados", resourceCulture);
            }
        }

        internal static string StockConfirmado
        {
            get
            {
                return ResourceManager.GetString("StockConfirmado", resourceCulture);
            }
        }
        
        internal static string direccion
        {
            get
            {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }

        internal static string telefono
        {
            get
            {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }

        internal static string Guardar
        {
            get
            {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }

        internal static string Cancelar
        {
            get
            {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }

        internal static string Generar
        {
            get
            {
                return ResourceManager.GetString("Generar", resourceCulture);
            }
        }


        // ######### VISTA CARRITO DE COMPRAS #############

        internal static string MontoTotal
        {
            get
            {
                return ResourceManager.GetString("MontoTotal", resourceCulture);
            }
        }

        // ######### VISTA PEDIDOS #############
        internal static string NroPedido
        {
            get
            {
                return ResourceManager.GetString("NroPedido", resourceCulture);
            }
        }

        internal static string Fecha
        {
            get
            {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }

        internal static string Estado
        {
            get
            {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }

        internal static string CantidadProductos
        {
            get
            {
                return ResourceManager.GetString("CantidadProductos", resourceCulture);
            }
        }

        internal static string NombreCliente
        {
            get
            {
                return ResourceManager.GetString("NombreCliente", resourceCulture);
            }
        }

        internal static string idPedido
        {
            get
            {
                return ResourceManager.GetString("idPedido", resourceCulture);
            }
        }

        internal static string opcionDePago
        {
            get
            {
                return ResourceManager.GetString("opcionDePago", resourceCulture);
            }
        }

        internal static string Codigo
        {
            get
            {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        internal static string Id_Busqueda
        {
            get
            {
                return ResourceManager.GetString("Id_Busqueda", resourceCulture);
            }
        }

        

        internal static string Ubicacion
        {
            get
            {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }

        internal static string UbicacionFoto
        {
            get
            {
                return ResourceManager.GetString("UbicacionFoto", resourceCulture);
            }
        }

        internal static string Categoria
        {
            get
            {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }

        internal static string Cantidad
        {
            get
            {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }

        internal static string CostoPublico
        {
            get
            {
                return ResourceManager.GetString("CostoPublico", resourceCulture);
            }
        }

        internal static string CostoReal
        {
            get
            {
                return ResourceManager.GetString("CostoReal", resourceCulture);
            }
        }

        internal static string Referencia
        {
            get
            {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }

        internal static string Puesto
        {
            get
            {
                return ResourceManager.GetString("Puesto", resourceCulture);
            }
        }

        internal static string CostoReposicion
        {
            get
            {
                return ResourceManager.GetString("CostoReposicion", resourceCulture);
            }
        }

        internal static string IDPromocion
        {
            get
            {
                return ResourceManager.GetString("IDPromocion", resourceCulture);
            }
        }

        internal static string FechaGeneracion
        {
            get
            {
                return ResourceManager.GetString("FechaGeneracion", resourceCulture);
            }
        }

        internal static string Activo
        {
            get
            {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }

        internal static string Descripcion
        {
            get
            {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        internal static string FechaPublicacion
        {
            get
            {
                return ResourceManager.GetString("FechaPublicacion", resourceCulture);
            }
        }

        

        internal static string Descuento
        {
            get
            {
                return ResourceManager.GetString("Descuento", resourceCulture);
            }
        }

        internal static string CostoConDescuento
        {
            get
            {
                return ResourceManager.GetString("CostoConDescuento", resourceCulture);
            }
        }
        
        internal static string PrecioTotal
        {
            get
            {
                return ResourceManager.GetString("PrecioTotal", resourceCulture);
            }
        }

        internal static string DetalleDePedido
        {
            get
            {
                return ResourceManager.GetString("DetalleDePedido", resourceCulture);
            }
        }

        internal static string DatosDeCliente
        {
            get
            {
                return ResourceManager.GetString("DatosDeCliente", resourceCulture);
            }
        }

        internal static string ListadoDeProductos
        {
            get
            {
                return ResourceManager.GetString("ListadoDeProductos", resourceCulture);
            }
        }

        internal static string ListadoDePromociones
        {
            get
            {
                return ResourceManager.GetString("ListadoDePromociones", resourceCulture);
            }
        }

        internal static string Buscar
        {
            get
            {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }

        internal static string Cliente
        {
            get
            {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }

        internal static string Sucursal
        {
            get
            {
                return ResourceManager.GetString("Sucursal", resourceCulture);
            }
        }

        internal static string Letra
        {
            get
            {
                return ResourceManager.GetString("Letra", resourceCulture);
            }
        }

        internal static string Numero
        {
            get
            {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
    }
}
